apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: api
  labels:
    app: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
       app: api-server
  template:
    metadata:
     labels:
       app: api-server
       tier: web
    spec:
      containers:
      - image: connorg/struts:0.0.1
        name: api
        ports:
        - containerPort: 8080
        securityContext:
          readOnlyRootFilesystem: true
      #   volumeMounts:
      #   - name: tmp
      #     mountPath: /usr/local/tomcat
      # volumes:
      # - name: tmp
      #   emptyDir: {}
      terminationGracePeriodSeconds: 0
