apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ping
  labels:
    app: ping
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: ping
  template:
    metadata:
      labels:
        app: ping
    spec:
      containers:
      - image: connorgorman/bsides2019:latest
        imagePullPolicy: Always
        name: ping
        command: ["ping", "google.com"]
        securityContext:
          capabilities:
            drop:
              - all
            add:
              - NET_RAW
