apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - image: connorgorman/bsides2019:latest
        imagePullPolicy: Always
        name: ubuntu
        command: ["sleep", "10000"]
